version: '3'
services:
  nginx:
    build: ./config/nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - static_volume:/static
      - ./etc/:/etc/ssl
    image: 550581268183.dkr.ecr.ap-northeast-2.amazonaws.com/hufs-sports-live-web:latest
    depends_on:
      - web
    platform: linux/amd64
  web:
    build:
      context: .
      dockerfile: ./config/web/Dockerfile
    volumes:
      - static_volume:/project/data/static
      - ./:/code
    command: ["./config/scripts/docker_compose_command.sh"]
    ports:
      - "8000:8000"
    platform: linux/amd64
    image: 550581268183.dkr.ecr.ap-northeast-2.amazonaws.com/hufs-sports-live-nginx:latest
    environment:
      - DJANGO_SETTINGS_MODULE=sports_live.settings.prod
    env_file:
      - .env
volumes:
  static_volume:
